### ISSUE TITLE
축제DB 파일 정리하기

### ISSUE THREAD

**Issue by baeknamju125** [baeknamju125/FestivalWhere#4]
- [x] 축제 정보를 데이터 파일을 이용하여 다운받아 엑셀에 지역별로 정리
- [ ] BaseActivity 상속받아 ui 만들기
- [x] 축제어디가 코드 파이어베이스 기반 코드에 넣어 만들어보기
- [ ] 구글 계정 정보 조회

**Comment by baeknamju125** [comment]
[축제 모음.xlsx](https://github.com/baeknamju125/FestivalWhere/files/491224/default.xlsx)

**Comment by KimHyeLime** [comment]
정리된 축제 json 파일. 키가 해시처리되어 있음. 구체적인 해시 생성 방법은 php api 서버 참고
http://festivalwhere.emirim.kr/api/festivals.json
