### ISSUE TITLE
축제 사진은 관리자가 직접 구해서 사이즈 크기를 줄여서 서버에 올린다.

### ISSUE THREAD

**Issue by progh2** [baeknamju125/FestivalWhere#9]

**Comment by baeknamju125** [comment]
![00fa9800516e67aef724e9df00a2f1c7](https://cloud.githubusercontent.com/assets/18460720/18814436/7b7aad20-834e-11e6-8dc1-820f00a2904a.jpg)

**Comment by baeknamju125** [comment]
https://learnfirebase-828fb.firebaseapp.com/posters/키값.jpg
